name: 运行定时脚本

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run-my-script:
    runs-on: ubuntu-22.04 

    steps:
      - name: 检出代码
        uses: actions/checkout@v4 

      - name: 设置 Python 3.9
        uses: actions/setup-python@v5 
        with:
          # 只写 3.9，让系统自动匹配 3.9 系列最新版
          python-version: '3.9' 

      - name: 安装依赖
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 运行 Python 脚本
        run: python sms.py
